# Site settings
title: Malia Gehan Github
baseurl: ''
# url: http://maliagehan.github.io/maliagehan

# Build settings
markdown: redcarpet
highlighter: pygments

# Jekyll-Bootstrap
JB:
    version: 2.0.3
    BASE_PATH : http://maliagehan.github.io/maliagehan
